# fly.toml app configuration file generated for lootsplitbot-discord on 2025-01-26T00:07:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lootsplitbot-discord'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
